export * from './requests/authRequest';
export * from './requests/courseRequest';
export * from './requests/paginatorRequest';
export * from './requests/professorRequest';
export * from './requests/studentRequest';
export * from './requests/subjectRequest';
export * from './requests/userRequest';
export * from './requests/subjectHistoryRequest';
export * from './requests/academicCareerRequest';

export * from './responses/courseResponse';
export * from './responses/errorResponse';
export * from './responses/genericResponse';
export * from './responses/professorResponse';
export * from './responses/studentResponse';
export * from './responses/subjectResponse';
export * from './responses/userResponse';
export * from './responses/subjectHistoryResponse';
export * from './responses/academicCareerResponse';
