import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { User } from '../services/tutor';

type AuthState = {
  user: User | null,
  token: string | null
}

const authSlice = createSlice({
  name: 'auth',
  initialState: { user: null, token: null } as AuthState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setCredentials: (
      state,
      { payload: { data, token }}: PayloadAction<{data: User; token: string}>,
    ) => {
      state.user = data;
      state.token = token;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

// Action creators are generated for each case reducer function
export const { setCredentials } = authSlice.actions;

export default authSlice.reducer;
